{{- range .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels: { app: {{ .name }} }
  template:
    metadata:
      labels: { app: {{ .name }} }
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: {{ .containerPort | default 8080 }}
          readinessProbe:
            httpGet:
              path: {{ .readinessPath | default "/health" }}
              port: {{ .containerPort | default 8080 }}
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .livenessPath | default "/live" }}
              port: {{ .containerPort | default 8080 }}
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  selector: { app: {{ .name }} }
  ports:
    - name: http
      port: 80
      targetPort: {{ .containerPort | default 8080 }}
{{- end }}
