CREATE SCHEMA IF NOT EXISTS chats;

CREATE TABLE IF NOT EXISTS chats.chats
(
    id bigint generated by default as identity
        constraint pk_chats
            PRIMARY KEY,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    is_disabled boolean default false
);


CREATE TABLE IF NOT EXISTS chats.participants
(
    chat_id bigint not null
        constraint fk_chat_id
            references chats.chats
            on delete restrict,
    user_id bigint not null
        constraint fk_user_id
            references identity.users
            on delete restrict,
    CONSTRAINT pk_participants PRIMARY KEY (chat_id, user_id)
);


CREATE TABLE IF NOT EXISTS chats.practices
(
    chat_id bigint not null
        constraint fk_chat_id
            references chats.chats
            on delete restrict,
    practice_id bigint not null
        constraint fk_practice_id
            references practices.practices
            on delete restrict,
    CONSTRAINT pk_practices PRIMARY KEY (chat_id, practice_id)
);


CREATE TABLE IF NOT EXISTS chats.lessons_parts
(
    chat_id bigint not null
        constraint fk_chat_id
            references chats.chats
            on delete restrict,
    lesson_part_id bigint not null
        constraint fk_practice_id
            references courses.lessons_parts
            on delete restrict,
    CONSTRAINT pk_lessons_parts PRIMARY KEY (lesson_part_id, chat_id)
);


CREATE TABLE IF NOT EXISTS chats.messages
(
    id bigint generated by default as identity
        constraint pk_message
            PRIMARY KEY,
    guid_id uuid not null,
    user_id bigint not null
        constraint fk_user_id
            references identity.users
            on delete restrict,
    reply_id bigint 
        constraint fk_reply_id
            references chats.messages
            on delete restrict,
    data text,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);