CREATE SCHEMA IF NOT EXISTS reference;

CREATE TABLE IF NOT EXISTS reference.levels
(

    id          bigint generated by default as identity
        constraint pk_levels
        PRIMARY KEY,
    title       varchar(255) not null,
    alias       varchar(255) not null,
    public_description text,
    comment text
);

