CREATE SCHEMA IF NOT EXISTS tags;

CREATE TABLE IF NOT EXISTS tags.tags
(

    id          bigint generated by default as identity
        constraint pk_tags
        PRIMARY KEY,
    title       varchar(255) not null,
    alias       varchar(255) not null,
    public_description text,
    comment text
);


CREATE INDEX IF NOT EXISTS idx_title ON tags.tags(title);